
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Image;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Faisal
 */
public class Teacher_Request extends javax.swing.JFrame {

    /**
     * Creates new form Teacher_Request
     */
    String url = "jdbc:mysql://localhost:3306/tution_house";
    String username = "root";
    String pass = "123456";
    
    public Teacher_Request() {
        initComponents();
        SearchTutions();
        ScaleImage1();
        ScaleImage2();
    }
    public void ScaleImage1() {
        ImageIcon ic;
        ic = new ImageIcon("E:\\JavaProject\\NoakhaliTuitionHousee\\src\\img\\back1.jpg");
        Image im = ic.getImage();
        Image imScale = im.getScaledInstance(jLabel11.getWidth(), jLabel11.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledicon = new ImageIcon(imScale);
        jLabel11.setIcon(scaledicon);
    }
    public void ScaleImage2() {
        ImageIcon ic;
        ic = new ImageIcon("E:\\JavaProject\\NoakhaliTuitionHousee\\src\\img\\back1.jpg");
        Image im = ic.getImage();
        Image imScale = im.getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledicon = new ImageIcon(imScale);
        jLabel10.setIcon(scaledicon);
    }
    class tution_info {

        public String code,cell,cls,subject,salary,category,days,time,location,gender,status;

        public tution_info(String code, String cell, String cls, String subject, String salary,
        String category,String days,String time,String location,String gender,String status) {
            this.code = code;
            this.cell = cell;
            this.cls = cls;
            this.subject= subject;
            this.salary = salary;
            this.category = category;
            this.days = days;
            this.time = time;
            this.location = location;
            this.gender= gender;
            this.status = status;
        }
    }
    ArrayList<tution_info> ar = new ArrayList<>();
    
    public void showTable() {
        DefaultTableModel mod = (DefaultTableModel) (jTable1.getModel());
        tcode.removeAllItems();
        tcode1.removeAllItems();
        tcode.addItem("Select");
        tcode1.addItem("Select");
        Object[] col = new Object[11];
        mod.setRowCount(0);
        for (int i = 0; i < ar.size(); i++) {
             if(ar.get(i).status.compareTo("Pending")==0 ){
                tcode.addItem(ar.get(i).code);
                tcode1.addItem(ar.get(i).code);
            }
            col[0] = ar.get(i).code;
            col[1] = ar.get(i).cell;
            col[2] = ar.get(i).cls;
            col[3] = ar.get(i).subject;
            col[4] = ar.get(i).salary;
            col[5] = ar.get(i).category;
            col[6] = ar.get(i).days;
            col[7] = ar.get(i).time;
            col[8] = ar.get(i).location;
            col[9] = ar.get(i).gender;
            col[10] = ar.get(i).status;
            mod.addRow(col);
        }
    }
    public void SearchTutions() {
        try {
            String query = "SELECT * FROM tutions;";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection(url, username, pass); //2
            Statement st = (Statement) con.createStatement();
            ResultSet rs = st.executeQuery(query);

            ar.clear();
            while (rs.next()) {
//                System.out.println(rs.getString("Code"));
                tution_info obj = new tution_info(rs.getString("Code"), rs.getString("mobile_no"),
                    rs.getString("class"), rs.getString("subject"), rs.getString("salary"),rs.getString("category"),
                    rs.getString("days"),rs.getString("time"),rs.getString("location"),rs.getString("t_gender"),rs.getString("status"));
                ar.add(obj);
            }
            showTable();
            st.close();
            con.close();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Teacher_Request.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tcode1 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tcode = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Mobile No", "Class", "       Subject", "Salary", "Category", "Days", "Time", "Location", "Gender", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jTable1.setSelectionForeground(new java.awt.Color(204, 255, 255));
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(10).setPreferredWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1092, -1));

        tcode1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        getContentPane().add(tcode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 445, 340, 32));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 489, 250, 34));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 588, 250, 32));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 536, 250, 34));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 178, 90, 34));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 126, 181, 34));

        jLabel3.setText("Media Fee  ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 79, -1, 27));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 77, 168, 31));

        jLabel4.setText("Paid");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 77, -1, 31));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 77, 176, 31));

        jLabel1.setText("Tution Code");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 70, 32));

        tcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jPanel1.add(tcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 27, 168, 32));

        jLabel2.setText("Teacher Code");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 27, -1, 32));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 27, 176, 32));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1110, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 590, 230));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, 34));

        jButton4.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, 34));

        jButton5.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, 32));

        jLabel5.setText("Tuition Code ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 27));

        jLabel6.setText("Subject   ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 70, 60, -1));

        jLabel7.setText(" Salary  ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 110, 50, -1));

        jLabel8.setText("Days");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 240));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 500, 230));

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Code = (String) tcode1.getSelectedItem();
        String Subject = jTextField4.getText();
        if(Code=="Select"){
            JOptionPane.showMessageDialog(null, "Please select tution Code!!");
        }
        else if(Subject.length()==0){
            JOptionPane.showMessageDialog(null, "subject field can't be empty!");
        }
        else {
             try{
                  String query1 = "UPDATE tutions SET subject = '" + Subject + "' where Code = '" + Code + "';";
                  Class.forName("com.mysql.jdbc.Driver");
                  Connection con1 = (Connection) DriverManager.getConnection(url, username, pass); //2
                  Statement st1 = (Statement) con1.createStatement();
//                      System.out.println(query);
                  st1.execute(query1);
                  JOptionPane.showMessageDialog(null, "Updated Successfully!");
                  jTextField4.setText("");
                  con1.close();
                  st1.close();
                  SearchTutions();
                      
             } catch (ClassNotFoundException ex) {
                Logger.getLogger(Teacher_Request.class.getName()).log(Level.SEVERE, null, ex);
             }catch (SQLException ex) {
                Logger.getLogger(Teacher_Request.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String Code = (String) tcode1.getSelectedItem();
        String days = jTextField5.getText();
        if(Code=="Select"){
            JOptionPane.showMessageDialog(null, "Please select tution Code!!");
        }
        else if(days.length()==0){
            JOptionPane.showMessageDialog(null, "subject field can't be empty!");
        }
        else {
             try{
                  String query1 = "UPDATE tutions SET days = '" + days + "' where Code = '" + Code + "';";
                  Class.forName("com.mysql.jdbc.Driver");
                  Connection con1 = (Connection) DriverManager.getConnection(url, username, pass); //2
                  Statement st1 = (Statement) con1.createStatement();
//                      System.out.println(query);
                  st1.execute(query1);
                  JOptionPane.showMessageDialog(null, "Updated Successfully!");
                  jTextField5.setText("");
                  con1.close();
                  st1.close();
                  SearchTutions();
                      
             } catch (ClassNotFoundException ex) {
                Logger.getLogger(Teacher_Request.class.getName()).log(Level.SEVERE, null, ex);
             }catch (SQLException ex) {
                Logger.getLogger(Teacher_Request.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String Code = (String) tcode1.getSelectedItem();
        String salary = jTextField6.getText();
        if(Code=="Select"){
            JOptionPane.showMessageDialog(null, "Please select tution Code!!");
        }
        else if(salary.length()==0){
            JOptionPane.showMessageDialog(null, "salary field can't be empty!");
        }
        else {
             try{
                  String query1 = "UPDATE tutions SET salary = '" + salary + "' where Code = '" + Code + "';";
                  Class.forName("com.mysql.jdbc.Driver");
                  Connection con1 = (Connection) DriverManager.getConnection(url, username, pass); //2
                  Statement st1 = (Statement) con1.createStatement();
//                      System.out.println(query);
                  st1.execute(query1);
                  JOptionPane.showMessageDialog(null, "Updated Successfully!");
                  jTextField6.setText("");
                  con1.close();
                  st1.close();
                  SearchTutions();
                      
             } catch (ClassNotFoundException ex) {
                Logger.getLogger(Teacher_Request.class.getName()).log(Level.SEVERE, null, ex);
             }catch (SQLException ex) {
                Logger.getLogger(Teacher_Request.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Code = (String) tcode.getSelectedItem();
        String Tcode = jTextField1.getText();
        String Fee = jTextField2.getText();
        String paid = jTextField3.getText();
        String Status;
        if(Fee == paid){
            Status="Done";
        }
        else{
            Status = "Pending";
        }
        if(Code=="Select"){
            JOptionPane.showMessageDialog(null, "Please select tution Code!!");
        }
        else if(Tcode.length()==0||Fee.length()==0||paid.length()==0){
            JOptionPane.showMessageDialog(null, "Fields can't be empty!");
        }
        else{
            try {
                String query1 = "SELECT mobile_no,salary FROM tutions where Code = '" + Code + "';";
                String query2 = "SELECT mobile FROM teachers where codded = '" + Tcode + "';";
                Class.forName("com.mysql.jdbc.Driver");
                Connection con1 = (Connection) DriverManager.getConnection(url, username, pass); //2
                Connection con2 = (Connection) DriverManager.getConnection(url, username, pass);
                Statement st1 = (Statement) con1.createStatement();
                Statement st2 = (Statement) con2.createStatement();
                ResultSet rs1 = st1.executeQuery(query1);
                ResultSet rs2 = st2.executeQuery(query2);
                if(rs2.next()){
                    String Gcell = null,salary = null;
                    if(rs1.next()){
                        Gcell = rs1.getString("mobile_no");
                        salary= rs1.getString("salary");
                    }
                    String Tcell= rs2.getString("mobile");

                    try {
                        String query = "INSERT INTO Details VALUES('" + Code + "','" + Tcode + "','" + Gcell
                        + "','" + Tcell + "','" + salary + "','" + Fee + "','" + paid
                        + "','" + Status + "');";
                        String q ="UPDATE tutions SET status = 'Done' where Code ='" + Code + "'";
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection con = (Connection) DriverManager.getConnection(url, username, pass); //2
                        Statement st = (Statement) con.createStatement();
                        Connection conn = (Connection) DriverManager.getConnection(url, username, pass); //2
                        Statement stt = (Statement) conn.createStatement();
//                        System.out.println(query);
                        st.execute(query);
                        stt.execute(q);
                        JOptionPane.showMessageDialog(null, "Infromation Added Successfully!");
                        SearchTutions();
                        st.close();
                        con.close();
                        stt.close();
                        conn.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(Teacher_Request.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Please Enter A valid Teacher Code!");
                }
                st1.close();
                st2.close();
                con1.close();
                con2.close();

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Teacher_Request.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AdminPage AP = new AdminPage();
        AP.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_Request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_Request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_Request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_Request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher_Request().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JComboBox<String> tcode;
    private javax.swing.JComboBox<String> tcode1;
    // End of variables declaration//GEN-END:variables
}
